baseURL = 'https://progrocket.dev/'
languageCode = 'ru-ru'
title = 'Progrocket Blog'

enableEmoji = true
defaultContentLanguage = "ru-ru"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'hrdark'
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true
    [markup.tableOfContents]
      startLevel = 2 # ToC starts from H2
      endLevel = 4 # ToC ends at H4
      ordered = true # generates <ul> instead of <ol>

[Languages.ru-ru]
  languageName = "Russian"
  languageCode = "ru-ru"
  contentDir = "content/ru"
  weight = 1

  [Languages.ru-ru.menu]
  [[Languages.ru-ru.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Главная'
    url = '/'
    weight = 10
  [[Languages.ru-ru.menu.main]]
    pageRef="posts"
    name = 'Посты'
    url = '/posts'
    weight = 20
  [[Languages.ru-ru.menu.main]]
    pageRef="about"
    name = 'О себе'
    url = '/about'
    weight = 30

[Languages.ru-ru.params]
  sitename = "Progrocket Development Blog"
  defaultColor = "auto" # set default color mode: dark or light or auto
  description = "Блог о моем проекте Servocket 🚀, разработке сетевых систем 🖧, распределенных вычислений 🖥️ и backend-разработке на .NET и PostgreSQL"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents globally
  goToTop = true # set to false to disable 'go to top' button
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[Languages.ru-ru.params.author]
  avatar = "anon-avatar.png"
  intro = "Progrocket Development Blog"
  name = "Dmitry aka Progrocket 🚀"
  description = "Блог о моем проекте Servocket 🚀, разработке сетевых систем 🖧, распределенных вычислений 🖥️ и backend-разработке на .NET и не только"

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true